-- public.accevent definition

-- Drop table

--DROP TABLE public.accevent;

CREATE TABLE public.accevent (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	creationdate timestamp NULL,
	description varchar(255) NULL,
	"name" varchar(255) NULL,
	note varchar(255) NULL,
	updatedate timestamp NULL,
	account_id int8 NULL,
	CONSTRAINT accevent_pkey PRIMARY KEY (id)
);


-- public.accevent foreign keys

ALTER TABLE public.accevent ADD CONSTRAINT fkfp3f1i42avlfv7763wchx45cu FOREIGN KEY (account_id) REFERENCES public.account(id);



