-- public."location" definition

-- Drop table

-- DROP TABLE public."location";

CREATE TABLE public."location" (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	latitud int8 NULL,
	longitud int8 NULL,
	CONSTRAINT location_pkey PRIMARY KEY (id)
);

-- public.account definition

-- Drop table

-- DROP TABLE public.account;

CREATE TABLE public.account (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	creationdate timestamp NULL,
	email varchar(255) NULL,
	lastname varchar(255) NULL,
	name varchar(255) NULL,
	updatedate timestamp NULL,
	location_id int8 NULL,
	CONSTRAINT account_pkey PRIMARY KEY (id)
);


-- public.account foreign keys

ALTER TABLE public.account ADD CONSTRAINT fkkw0h873hsajegawpc96lp3hvp FOREIGN KEY (location_id) REFERENCES public."location"(id);